//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.3, generator: @autorest/go@4.0.0-preview.44)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package xapis

const host = "https://api.growingbox.cn"

// StorageProvider - 云存储服务商
type StorageProvider string

const (
	StorageProviderAliyun StorageProvider = "aliyun"
	StorageProviderQcloud StorageProvider = "qcloud"
)

// PossibleStorageProviderValues returns the possible values for the StorageProvider const type.
func PossibleStorageProviderValues() []StorageProvider {
	return []StorageProvider{	
		StorageProviderAliyun,
		StorageProviderQcloud,
	}
}

