/*
xapi services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xapis

import (
	"encoding/json"
)

// VideoInfo struct for VideoInfo
type VideoInfo struct {
	// 视频时长（秒）
	Duration int32 `json:"duration"`
	// 视频宽度（像素）
	Width int32 `json:"width"`
	// 视频高度（像素）
	Height int32 `json:"height"`
	// 视频大小（字节）
	Size int32 `json:"size"`
	// 视频格式
	Format *string `json:"format,omitempty"`
}

// NewVideoInfo instantiates a new VideoInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoInfo(duration int32, width int32, height int32, size int32) *VideoInfo {
	this := VideoInfo{}
	this.Duration = duration
	this.Width = width
	this.Height = height
	this.Size = size
	return &this
}

// NewVideoInfoWithDefaults instantiates a new VideoInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoInfoWithDefaults() *VideoInfo {
	this := VideoInfo{}
	return &this
}

// GetDuration returns the Duration field value
func (o *VideoInfo) GetDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Duration
}

// GetDurationOk returns a tuple with the Duration field value
// and a boolean to check if the value has been set.
func (o *VideoInfo) GetDurationOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Duration, true
}

// SetDuration sets field value
func (o *VideoInfo) SetDuration(v int32) {
	o.Duration = v
}

// GetWidth returns the Width field value
func (o *VideoInfo) GetWidth() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Width
}

// GetWidthOk returns a tuple with the Width field value
// and a boolean to check if the value has been set.
func (o *VideoInfo) GetWidthOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Width, true
}

// SetWidth sets field value
func (o *VideoInfo) SetWidth(v int32) {
	o.Width = v
}

// GetHeight returns the Height field value
func (o *VideoInfo) GetHeight() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Height
}

// GetHeightOk returns a tuple with the Height field value
// and a boolean to check if the value has been set.
func (o *VideoInfo) GetHeightOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Height, true
}

// SetHeight sets field value
func (o *VideoInfo) SetHeight(v int32) {
	o.Height = v
}

// GetSize returns the Size field value
func (o *VideoInfo) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *VideoInfo) GetSizeOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *VideoInfo) SetSize(v int32) {
	o.Size = v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *VideoInfo) GetFormat() string {
	if o == nil || isNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoInfo) GetFormatOk() (*string, bool) {
	if o == nil || isNil(o.Format) {
    return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *VideoInfo) HasFormat() bool {
	if o != nil && !isNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *VideoInfo) SetFormat(v string) {
	o.Format = &v
}

func (o VideoInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["duration"] = o.Duration
	}
	if true {
		toSerialize["width"] = o.Width
	}
	if true {
		toSerialize["height"] = o.Height
	}
	if true {
		toSerialize["size"] = o.Size
	}
	if !isNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	return json.Marshal(toSerialize)
}

type NullableVideoInfo struct {
	value *VideoInfo
	isSet bool
}

func (v NullableVideoInfo) Get() *VideoInfo {
	return v.value
}

func (v *NullableVideoInfo) Set(val *VideoInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoInfo(val *VideoInfo) *NullableVideoInfo {
	return &NullableVideoInfo{value: val, isSet: true}
}

func (v NullableVideoInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVideoInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


