/*
xapi services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xapis

import (
	"encoding/json"
)

// UpdateConfig struct for UpdateConfig
type UpdateConfig struct {
	// 所属的资源ID
	ResourceId *string `json:"resource_id,omitempty"`
	// 所属的配置组ID
	GroupId *string `json:"group_id,omitempty"`
	// 配置模板ID
	TemplateId *string `json:"template_id,omitempty"`
	// 配置项
	Key *string `json:"key,omitempty"`
	// 配置内容
	Value map[string]interface{} `json:"value,omitempty"`
}

// NewUpdateConfig instantiates a new UpdateConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateConfig() *UpdateConfig {
	this := UpdateConfig{}
	return &this
}

// NewUpdateConfigWithDefaults instantiates a new UpdateConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateConfigWithDefaults() *UpdateConfig {
	this := UpdateConfig{}
	return &this
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise.
func (o *UpdateConfig) GetResourceId() string {
	if o == nil || isNil(o.ResourceId) {
		var ret string
		return ret
	}
	return *o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConfig) GetResourceIdOk() (*string, bool) {
	if o == nil || isNil(o.ResourceId) {
    return nil, false
	}
	return o.ResourceId, true
}

// HasResourceId returns a boolean if a field has been set.
func (o *UpdateConfig) HasResourceId() bool {
	if o != nil && !isNil(o.ResourceId) {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given string and assigns it to the ResourceId field.
func (o *UpdateConfig) SetResourceId(v string) {
	o.ResourceId = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *UpdateConfig) GetGroupId() string {
	if o == nil || isNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConfig) GetGroupIdOk() (*string, bool) {
	if o == nil || isNil(o.GroupId) {
    return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *UpdateConfig) HasGroupId() bool {
	if o != nil && !isNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *UpdateConfig) SetGroupId(v string) {
	o.GroupId = &v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *UpdateConfig) GetTemplateId() string {
	if o == nil || isNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConfig) GetTemplateIdOk() (*string, bool) {
	if o == nil || isNil(o.TemplateId) {
    return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *UpdateConfig) HasTemplateId() bool {
	if o != nil && !isNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *UpdateConfig) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *UpdateConfig) GetKey() string {
	if o == nil || isNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConfig) GetKeyOk() (*string, bool) {
	if o == nil || isNil(o.Key) {
    return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *UpdateConfig) HasKey() bool {
	if o != nil && !isNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *UpdateConfig) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *UpdateConfig) GetValue() map[string]interface{} {
	if o == nil || isNil(o.Value) {
		var ret map[string]interface{}
		return ret
	}
	return o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateConfig) GetValueOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Value) {
    return map[string]interface{}{}, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *UpdateConfig) HasValue() bool {
	if o != nil && !isNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given map[string]interface{} and assigns it to the Value field.
func (o *UpdateConfig) SetValue(v map[string]interface{}) {
	o.Value = v
}

func (o UpdateConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ResourceId) {
		toSerialize["resource_id"] = o.ResourceId
	}
	if !isNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}
	if !isNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !isNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !isNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateConfig struct {
	value *UpdateConfig
	isSet bool
}

func (v NullableUpdateConfig) Get() *UpdateConfig {
	return v.value
}

func (v *NullableUpdateConfig) Set(val *UpdateConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateConfig(val *UpdateConfig) *NullableUpdateConfig {
	return &NullableUpdateConfig{value: val, isSet: true}
}

func (v NullableUpdateConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


