/*
xapi services

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package xapis

import (
	"encoding/json"
)

// CreateConfigGroup struct for CreateConfigGroup
type CreateConfigGroup struct {
	// 配置组名称
	Name string `json:"name"`
}

// NewCreateConfigGroup instantiates a new CreateConfigGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateConfigGroup(name string) *CreateConfigGroup {
	this := CreateConfigGroup{}
	this.Name = name
	return &this
}

// NewCreateConfigGroupWithDefaults instantiates a new CreateConfigGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateConfigGroupWithDefaults() *CreateConfigGroup {
	this := CreateConfigGroup{}
	return &this
}

// GetName returns the Name field value
func (o *CreateConfigGroup) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateConfigGroup) GetNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateConfigGroup) SetName(v string) {
	o.Name = v
}

func (o CreateConfigGroup) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateConfigGroup struct {
	value *CreateConfigGroup
	isSet bool
}

func (v NullableCreateConfigGroup) Get() *CreateConfigGroup {
	return v.value
}

func (v *NullableCreateConfigGroup) Set(val *CreateConfigGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateConfigGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateConfigGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateConfigGroup(val *CreateConfigGroup) *NullableCreateConfigGroup {
	return &NullableCreateConfigGroup{value: val, isSet: true}
}

func (v NullableCreateConfigGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateConfigGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


