//go:build go1.18
// +build go1.18

// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.9.3, generator: @autorest/go@4.0.0-preview.44)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// DO NOT EDIT.

package xapis

// ClientCreateConfigGroupResponse contains the response from method Client.CreateConfigGroup.
type ClientCreateConfigGroupResponse struct {
	ConfigGroup
}

// ClientCreateConfigResponse contains the response from method Client.CreateConfig.
type ClientCreateConfigResponse struct {
	Config
}

// ClientCreateConfigTemplateResponse contains the response from method Client.CreateConfigTemplate.
type ClientCreateConfigTemplateResponse struct {
	ConfigTemplate
}

// ClientDeleteConfigGroupResponse contains the response from method Client.DeleteConfigGroup.
type ClientDeleteConfigGroupResponse struct {
	// placeholder for future response values
}

// ClientDeleteConfigResponse contains the response from method Client.DeleteConfig.
type ClientDeleteConfigResponse struct {
	// placeholder for future response values
}

// ClientDeleteConfigTemplateResponse contains the response from method Client.DeleteConfigTemplate.
type ClientDeleteConfigTemplateResponse struct {
	// placeholder for future response values
}

// ClientGetConfigByKeyResponse contains the response from method Client.GetConfigByKey.
type ClientGetConfigByKeyResponse struct {
	Config
}

// ClientGetConfigGroupResponse contains the response from method Client.GetConfigGroup.
type ClientGetConfigGroupResponse struct {
	ConfigGroup
}

// ClientGetConfigResponse contains the response from method Client.GetConfig.
type ClientGetConfigResponse struct {
	Config
}

// ClientGetConfigTemplateByKeyResponse contains the response from method Client.GetConfigTemplateByKey.
type ClientGetConfigTemplateByKeyResponse struct {
	ConfigTemplate
}

// ClientGetConfigTemplateResponse contains the response from method Client.GetConfigTemplate.
type ClientGetConfigTemplateResponse struct {
	ConfigTemplate
}

// ClientGetStorageTemporaryCredentialsResponse contains the response from method Client.GetStorageTemporaryCredentials.
type ClientGetStorageTemporaryCredentialsResponse struct {
	StorageTemporaryCredentials
}

// ClientUpdateConfigGroupResponse contains the response from method Client.UpdateConfigGroup.
type ClientUpdateConfigGroupResponse struct {
	ConfigGroup
}

// ClientUpdateConfigResponse contains the response from method Client.UpdateConfig.
type ClientUpdateConfigResponse struct {
	Config
}

// ClientUpdateConfigTemplateResponse contains the response from method Client.UpdateConfigTemplate.
type ClientUpdateConfigTemplateResponse struct {
	ConfigTemplate
}

