openapi: 3.0.3
info:
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: xapi services
  version: 0.0.1
servers:
- url: https://api.growingbox.cn
- url: https://service-rjma2xb8-1252461817-in.gz.apigw.tencentcs.com:9009
tags:
- description: 通用配置服务
  name: config
- description: 云存储服务
  name: storage
- description: 短信服务
  name: sms
- description: silk语音编解码
  name: silk-codec
paths:
  /config/v1/configs:
    get:
      operationId: getConfigByKey
      security:
      - oauth2:
        - configs:read
      - bearer: []
      - apiKey: []
      summary: 根据配置项查询配置
      tags:
      - config
    post:
      operationId: createConfig
      security:
      - oauth2:
        - configs:write
      - bearer: []
      - apiKey: []
      summary: 创建配置
      tags:
      - config
  /config/v1/configs/{id}:
    delete:
      operationId: deleteConfig
      security:
      - oauth2:
        - configs:delete
      - bearer: []
      - apiKey: []
      summary: 删除配置
      tags:
      - config
    get:
      operationId: getConfig
      security:
      - oauth2:
        - configs:read
      - bearer: []
      - apiKey: []
      summary: 查询配置
      tags:
      - config
    patch:
      operationId: updateConfig
      security:
      - oauth2:
        - configs:write
      - bearer: []
      - apiKey: []
      summary: 更新配置
      tags:
      - config
  /config/v1/config_templates:
    get:
      operationId: getConfigTemplateByKey
      security:
      - oauth2:
        - configs:read
      - bearer: []
      - apiKey: []
      summary: 根据配置项查询配置模版
      tags:
      - config
    post:
      operationId: createConfigTemplate
      security:
      - oauth2:
        - configs:write
      - bearer: []
      - apiKey: []
      summary: 创建配置模版
      tags:
      - config
  /config/v1/config_templates/{id}:
    delete:
      operationId: deleteConfigTemplate
      security:
      - oauth2:
        - configs:delete
      - bearer: []
      - apiKey: []
      summary: 删除配置模板
      tags:
      - config
    get:
      operationId: getConfigTemplate
      security:
      - oauth2:
        - configs:read
      - bearer: []
      - apiKey: []
      summary: 查询配置模板
      tags:
      - config
    patch:
      operationId: updateConfigTemplate
      security:
      - oauth2:
        - configs:write
      - bearer: []
      - apiKey: []
      summary: 更新配置模板
      tags:
      - config
  /config/v1/config_groups:
    post:
      operationId: createConfigGroup
      security:
      - oauth2:
        - configs:write
      - bearer: []
      - apiKey: []
      summary: 创建配置组
      tags:
      - config
  /config/v1/config_groups/{id}:
    delete:
      operationId: deleteConfigGroup
      security:
      - oauth2:
        - configs:delete
      - bearer: []
      - apiKey: []
      summary: 删除配置组
      tags:
      - config
    get:
      operationId: getConfigGroup
      security:
      - oauth2:
        - configs:read
      - bearer: []
      - apiKey: []
      summary: 查询配置组
      tags:
      - config
    patch:
      operationId: updateConfigGroup
      security:
      - oauth2:
        - configs:write
      - bearer: []
      - apiKey: []
      summary: 更新配置组
      tags:
      - config
  /storage/v1/temporary_credentials:
    get:
      description: 获取上传文件临时凭证
      operationId: getStorageTemporaryCredentials
      security:
      - oauth2:
        - storage.credentials:read
      - bearer: []
      - apiKey: []
      summary: 获取上传文件临时凭证
      tags:
      - storage
  /storage/v1/video_info:
    get:
      description: 获取视频信息
      operationId: getVideoInfo
      security:
      - oauth2:
        - storage:read
      - bearer: []
      - apiKey: []
      summary: 获取视频信息
      tags:
      - storage
  /storage/v1/video_snapshot:
    get:
      description: 获取视频截图
      operationId: getVideoSnapshot
      security:
      - oauth2:
        - storage:read
      - bearer: []
      - apiKey: []
      summary: 获取视频截图
      tags:
      - storage
  /storage/v1/audio_info:
    get:
      description: 获取音频信息
      operationId: getAudioInfo
      security:
      - oauth2:
        - storage:read
      - bearer: []
      - apiKey: []
      summary: 获取音频信息
      tags:
      - storage
  /sms/v1/send:
    post:
      description: 发送短信
      operationId: sendSMS
      security:
      - oauth2:
        - sms:send
      - bearer: []
      - apiKey: []
      summary: 发送短信
      tags:
      - sms
  /silk/v3/encode:
    get:
      description: 将语音链接编码为silk-v3格式
      operationId: encodeSilkV3ByURL
      summary: 将语音链接编码为silk-v3格式
      tags:
      - silk-codec
    post:
      description: 将语音编码为silk-v3格式
      operationId: encodeSilkV3
      summary: 将语音编码为silk-v3格式
      tags:
      - silk-codec
  /silk/v3/decode:
    get:
      description: 将链接解码silk-v3格式的语音
      operationId: decodeSilkV3ByURL
      summary: 将链接解码silk-v3格式的语音
      tags:
      - silk-codec
    post:
      description: 解码silk-v3格式的语音
      operationId: decodeSilkV3
      summary: 解码silk-v3格式的语音
      tags:
      - silk-codec
components:
  securitySchemes:
    oauth2:
      flows:
        clientCredentials:
          scopes:
            configs:read: 读取配置、配置模版、配置组
            configs:write: 创建、更新配置、配置模版、配置组
            configs:delete: 删除配置、配置模版、配置组
            storage:read: 读取云存储资源
            storage.credentials:read: 获取云存储上传凭证
            sms:send: 发送短信
          tokenUrl: https://mofan.cn.authok.cn/oauth/token
      type: oauth2
    bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
    apiKey:
      in: header
      name: X-Client-ID
      type: apiKey
