openapi: 3.0.3
info:
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: xapi services
  version: 0.0.1
servers:
- url: https://api.growingbox.cn
tags:
- description: 通用配置
  name: config
- description: 云存储相关
  name: storage
paths:
  /config/v1/configs:
    get:
      operationId: getConfigByKey
      security:
      - oauth2:
        - configs:read
      - bearer: []
      summary: 根据配置项查询配置
      tags:
      - config
    post:
      operationId: createConfig
      security:
      - oauth2:
        - configs:write
      - bearer: []
      summary: 创建配置
      tags:
      - config
  /config/v1/configs/{id}:
    delete:
      operationId: deleteConfig
      security:
      - oauth2:
        - configs:delete
      - bearer: []
      summary: 删除配置
      tags:
      - config
    get:
      operationId: getConfig
      security:
      - oauth2:
        - configs:read
      - bearer: []
      summary: 查询配置
      tags:
      - config
    patch:
      operationId: updateConfig
      security:
      - oauth2:
        - configs:write
      - bearer: []
      summary: 更新配置
      tags:
      - config
  /config/v1/config_templates:
    get:
      operationId: getConfigTemplateByKey
      security:
      - oauth2:
        - configs:read
      - bearer: []
      summary: 根据配置项查询配置模版
      tags:
      - config
    post:
      operationId: createConfigTemplate
      security:
      - oauth2:
        - configs:write
      - bearer: []
      summary: 创建配置模版
      tags:
      - config
  /config/v1/config_templates/{id}:
    delete:
      operationId: deleteConfigTemplate
      security:
      - oauth2:
        - configs:delete
      - bearer: []
      summary: 删除配置模板
      tags:
      - config
    get:
      operationId: getConfigTemplate
      security:
      - oauth2:
        - configs:read
      - bearer: []
      summary: 查询配置模板
      tags:
      - config
    patch:
      operationId: updateConfigTemplate
      security:
      - oauth2:
        - configs:write
      - bearer: []
      summary: 更新配置模板
      tags:
      - config
  /config/v1/config_groups:
    post:
      operationId: createConfigGroup
      security:
      - oauth2:
        - configs:write
      - bearer: []
      summary: 创建配置组
      tags:
      - config
  /config/v1/config_groups/{id}:
    delete:
      operationId: deleteConfigGroup
      security:
      - oauth2:
        - configs:delete
      - bearer: []
      summary: 删除配置组
      tags:
      - config
    get:
      operationId: getConfigGroup
      security:
      - oauth2:
        - configs:read
      - bearer: []
      summary: 查询配置组
      tags:
      - config
    patch:
      operationId: updateConfigGroup
      security:
      - oauth2:
        - configs:write
      - bearer: []
      summary: 更新配置组
      tags:
      - config
  /storage/v1/temporary_credentials:
    get:
      description: 获取上传文件临时凭证
      operationId: getStorageTemporaryCredentials
      security:
      - oauth2:
        - storage.credentials:read
      - bearer: []
      summary: 获取上传文件临时凭证
      tags:
      - storage
components:
  securitySchemes:
    oauth2:
      flows:
        clientCredentials:
          scopes:
            configs:read: 读取配置、配置模版、配置组
            configs:write: 创建、更新配置、配置模版、配置组
            configs:delete: 删除配置、配置模版、配置组
            storage.credentials:read: 获取云存储上传凭证
          tokenUrl: https://mofan.cn.authok.cn/oauth/token
      type: oauth2
    bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
